### ISSUE TITLE
Enhance Docker Development Configuration

### ISSUE THREAD

**Issue by rgottardi** [rgottardi/template-mernpern-starter#11]
We need to enhance the Docker configuration to support various development scenarios and improve the development experience.

### Docker Compose Configurations
- [ ] Add multiple Docker Compose configurations:
  ```yaml
  # docker-compose.yml (base configuration)
  version: '3.8'
  services:
    mongodb:
      image: mongo:latest
      ports: ['27017:27017']
      volumes: ['mongodb_data:/data/db']

  # docker-compose.dev.yml (development overrides)
  version: '3.8'
  services:
    client:
      build:
        context: ./client
        dockerfile: Dockerfile.dev
      volumes:
        - ./client:/app
        - /app/node_modules
      ports: ['5173:5173']
      environment:
        - NODE_ENV=development
    
    server:
      build:
        context: ./server
        dockerfile: Dockerfile.dev
      volumes:
        - ./server:/app
        - /app/node_modules
      ports: ['3000:3000']
      environment:
        - NODE_ENV=development
  ```

### Development Services
- [ ] Add optional development services:
  ```yaml
  # docker-compose.tools.yml
  services:
    mailhog:
      image: mailhog/mailhog
      ports: ['1025:1025', '8025:8025']
    
    redis:
      image: redis:alpine
      ports: ['6379:6379']
    
    mongo-express:
      image: mongo-express
      ports: ['8081:8081']
      environment:
        - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
  ```

### Docker Scripts
- [ ] Create Docker management scripts:
  ```bash
  #!/bin/bash
  # scripts/docker/dev.sh
  docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d

  # scripts/docker/tools.sh
  docker compose -f docker-compose.yml -f docker-compose.tools.yml up -d

  # scripts/docker/clean.sh
  docker compose down -v
  docker system prune -f
  ```

### Volume Management
- [ ] Add volume management:
  - [ ] Named volumes for databases
  - [ ] Bind mounts for development
  - [ ] Volume cleanup scripts
  - [ ] Data persistence configuration

### Development Tools
- [ ] Add development tool configurations:
  - [ ] Debugger setup
  - [ ] Hot reloading
  - [ ] Source maps
  - [ ] Development SSL

### Documentation
- [ ] Add Docker documentation:
  - [ ] Development setup guide
  - [ ] Available services
  - [ ] Volume management
  - [ ] Debugging instructions
  - [ ] Common issues
